apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-pokemon-server
  labels:
    app: my-pokemon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pokemon-server
  template:
    metadata:
      labels:
        app: my-pokemon-server
    spec:
      containers:
      - name: my-pokemon-server
        image: josephck1997/my-pokemon-server:latest
        envFrom:
          - configMapRef:
              name: app-env
        ports:
        - containerPort: 3000