apiVersion: v1
kind: Service
metadata:
  name: my-pokemon-server-service
spec:
  selector:
    app: my-pokemon-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110