apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-pokemon-server-prod
  labels:
    app: my-pokemon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pokemon-server
  template:
    metadata:
      labels:
        app: my-pokemon-server
    spec:
      containers:
      - name: my-pokemon-server
        image: josephck1997/my-pokemon-server:latest
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
            name: ../environment/local-all.env