services:
  my-pokemon-server:
    image: josephck1997/my-pokemon-server
    restart: always
    container_name: my-pokemon-server
    env_file: ../../environment/local-all.env
    ports:
      - 3000:3000